name: fan_carousel_image_slider
description: A fantasy carousel slider widget. only for displaying online and local images.
version: 1.3.0
homepage: https://github.com/marjandn/fan_carousel_image_slider

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_image_viewer: ^1.5.1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: "This screenshot shows the first type of fan carousel image slider"
    path: screenshots/fan_carousel_image_slider_type1.jpg
  - description: "This screenshot shows the second type of fan carousel image slider"
    path: screenshots/fan_carousel_image_slider_type2.jpg

flutter:
